name: Examen2

on:
  pull_request:
    branches: [ main ]
    paths:
      - src/**

jobs:
  check:  
    name: checkfor status 200
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: text
        uses: johnlokerse/website-healthcheck@v2
        with:
          web-url: "http://${{ secrets.AWS_IP}}/docs"
          scan-for-text: "FastAPI"
  check2:  
    name: checkfor status 200
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - id: text
        uses: johnlokerse/website-healthcheck@v2
        with:
          web-url: "http://${{ secrets.AWS_IP}}/students/1"
          scan-for-text: "name"
  check3:  
    name: checkfor status 200
    runs-on: ubuntu-latest
    needs: check2
    steps:
      - uses: actions/checkout@v2
      - id: text
        uses: johnlokerse/website-healthcheck@v2
        with:
          web-url: "http://${{ secrets.AWS_IP}}/status"
          scan-for-text: "status"
